Repository QuasarApp/CopyrightFixer, pull requests merged in 2021-05, with the labels that each got.

#57 "added description for the Signature class"
  src/CopyrighFixer/CopyrighFixer/sign.h
  tests/units/signtest.cpp
Labels: bug, documentation

#56 Add support to a parsing of signature files.
  src/CopyrighFixer/CopyrighFixer/owner.cpp
  src/CopyrighFixer/CopyrighFixer/owner.h
  src/CopyrighFixer/CopyrighFixer/sign.cpp
  src/CopyrighFixer/CopyrighFixer/sign.h
  tests/tstMain.cpp
  tests/units/signtest.cpp
  tests/units/signtest.h
Labels: enhancement

#55 Change bugfix - move helpCall method into worker class.
  src/CFixer/main.cpp
  src/CopyrighFixer/CopyrighFixer/owner.h
  src/CopyrighFixer/CopyrighFixer/worker.cpp
  src/CopyrighFixer/CopyrighFixer/worker.h
Labels: bug

#53 Added a Signer class.
  src/CopyrighFixer/CopyrighFixer/signer.cpp
  src/CopyrighFixer/CopyrighFixer/signer.h
  tests/units/signertest.cpp
  tests/units/signertest.h
Labels: enhancement

#54 Added the ConfigParser class
  src/CopyrighFixer/CopyrighFixer/configparser.cpp
  src/CopyrighFixer/CopyrighFixer/configparser.h
  tests/tstMain.cpp
  tests/units/configparsertest.cpp
  tests/units/configparsertest.h
Labels: enhancement

#64 Fixing bugs: added comments for all test methods.
  tests/units/configparsertest.cpp
  tests/units/signtest.cpp
Labels: enhancement

#52 Create main class Worker
  src/CFixer/main.cpp
  src/CopyrighFixer/CopyrighFixer/worker.cpp
  src/CopyrighFixer/CopyrighFixer/worker.h
Labels: enhancement

#66 Remove the currentOwner opt.
  README.md
  src/CopyrighFixer/CopyrighFixer/config.cpp
  src/CopyrighFixer/CopyrighFixer/config.h
  tests/units/configparsertest.h
Labels: bug

#67 Create a interface class for working wit source file.
  src/CopyrighFixer/CopyrighFixer/ifilemanager.cpp
  src/CopyrighFixer/CopyrighFixer/ifilemanager.h
Labels: enhancement

#69 Fixing bug: Move comments.
  src/CopyrighFixer/CopyrighFixer/ifilemanager.h
Labels: bug, documentation
