Repository QuasarApp/CopyrightFixer, pull requests merged in 2021-04, with the labels that each got.

#16 Task 13 Remove the CopyrighFixerModule
  src/CopyrighFixer/CopyrighFixer.qrc
  src/CopyrighFixer/CopyrighFixerModule/CopyrighFixer.qml
  src/CopyrighFixer/CopyrighFixerModule/qmldir
Labels: enhancement, good first issue

#18 Add banner in readme
  README.md
  res/CopyrighFixerBanner_web.png
  res/CopyrighFixer_web.png
Labels: documentation

#21 doxygen.conf fix tag INPUT
  doxygen.conf
Labels: documentation

#24 Change qr code
  README.md
  res/qr.png
Labels: documentation

#25 fix wasm build
  src/CMakeLists.txt
Labels: bug

#31 Using QuasarAppLib::Help
  src/CFixer/main.cpp
Labels: enhancement

#36 doxygen settings change
  doxygen.conf
Labels: documentation

#34 Created class about information owner
  src/CopyrighFixer/CopyrighFixer/owner.cpp
  src/CopyrighFixer/CopyrighFixer/owner.h
Labels: enhancement

#41 Fix cmake lists after moving submodules
  .gitignore
  CMakeLists.txt
  src/CFixer/CMakeLists.txt
  src/CMakeLists.txt
  src/CopyrighFixer/CMakeLists.txt
  tests/CMakeLists.txt
Labels: bug

#39 Created a class for collect information about signature.
  src/CopyrighFixer/CopyrighFixer/sign.cpp
  src/CopyrighFixer/CopyrighFixer/sign.h
Labels: enhancement

#43 Fixing: add const reference into getOwnerName.
  src/CopyrighFixer/CopyrighFixer/owner.cpp
  src/CopyrighFixer/CopyrighFixer/owner.h
Labels: enhancement

#44 Added class for collect session conf
  src/CopyrighFixer/CopyrighFixer/config.cpp
  src/CopyrighFixer/CopyrighFixer/config.h
  src/CopyrighFixer/CopyrighFixer/sign.h
Labels: enhancement

#47 Rename all private fields
  src/CopyrighFixer/CopyrighFixer/config.cpp
  src/CopyrighFixer/CopyrighFixer/config.h
  src/CopyrighFixer/CopyrighFixer/owner.cpp
  src/CopyrighFixer/CopyrighFixer/owner.h
  src/CopyrighFixer/CopyrighFixer/sign.cpp
  src/CopyrighFixer/CopyrighFixer/sign.h
Labels: bug

#48 Added arhitecture plan
  README.md
  res/architecture.qmodel
  res/general application arhitecture.png
Labels: documentation
